basepath = "cust_helpers"
smb_path = f"{basepath}/smb_usecases.yaml"
agent_template = f"{basepath}/agent_templates.yaml"
play_template = f"{basepath}/playbook_templates.yaml"
conv_template = f"{basepath}/conversation_template.yaml"
search_email_template = f"{basepath}/search_template.yaml"
search_summary = f"{basepath}/email_summarize_template.yaml"